### ISSUE TITLE
Latest ElasticSearch 7.3.1 Version

### ISSUE THREAD

**Issue by dpatersondept** [magrossi/es-log4j2-appender#11]
Hi,
Thanks for creating this appender it is exactly what I am looking for. However, I downloaded and built the source and tried to use this and I get a null pointer exception when the appender tries to initialize the logger. I noticed that I was trying to use the appender with the latest ElasticSearch and saw that the RestClient was slightly different in its implementation. I updated the code locally to test if I could get it to work and updated the version of ElasticSearch in the POM but still, I get the same issue. The error I get is below:
```
Caused by: java.lang.NullPointerException
	at org.apache.commons.logging.LogFactory$Log4jLog.<init>(LogFactory.java:204)
	at org.apache.commons.logging.LogFactory$Log4jDelegate.createLog(LogFactory.java:166)
	at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:109)
	at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:99)
	at org.elasticsearch.client.RestClient.<clinit>(RestClient.java:97)
```

My appender settings are as follows:

```
<?xml version="1.0" encoding="UTF-8"?>
<Configuration status="DEBUG" strict="true" name="ElasticSearchAppender"
               packages="com.github.magrossi.log4j2.elasticsearch">
    <Appenders>
        <!-- Sends logs immediately -->
        <Appender type="ElasticSearch"
        name="ELASTIC"
        maxBulkSize="0"
        maxDelayTime="0"
        esIndex="process-api-log-"
        esType="logs"
        dateFormat="yyyyMMdd">
        <!-- ElasticSearch credentials, if required
        user="${env:myEsUser}"
        password="${env:myEsPassword}">-->
        <!-- List of nodes in your ElasticSearch cluster -->
            <Host type="HttpAddress" scheme="http" host="localhost" port="9200"/>
        </Appender>
        <RollingFile name="LogToRollingFile" fileName="logs/process-api.log"
                     filePattern="logs/$${date:yyyy-MM}/process-api-%d{MM-dd-yyyy}-%i.log.gz">
            <PatternLayout>
                <Pattern>%d %p %c{1.} [%t] %m%n</Pattern>
            </PatternLayout>
            <Policies>
                <TimeBasedTriggeringPolicy />
                <SizeBasedTriggeringPolicy size="10 MB"/>
            </Policies>
        </RollingFile>
    </Appenders>
    <Loggers>
        <Logger name="PROCESS_API_LOGGER" level="debug" additivity="false">
            <AppenderRef ref="LogToRollingFile"/>
            <AppenderRef ref="ELASTIC"/>
        </Logger>
        <Root level="ERROR">
            <AppenderRef ref="LogToRollingFile"/>
        </Root>
    </Loggers>
</Configuration>
```

Should the current version work with the latest ES? Its also worth noting that I do not have a password on my local ES instance I am testing with. Maybe that makes a difference or not I am not sure.

Thanks,

**Comment by magrossi** [comment]
It seems like they have removed `type` in ElasticSearch 7, so I don't think this is compatible. You would need to update the Gradle ES client dependency and remove the type from the code. I'm happy to accept a PR if you'd like to implement this.
